package ticketmachine;

public enum Operation {
    SELLING_TICKET, SELECTING_PAYMENT, BUYING_SINGLE,BUYING_SEASON, BUYING_PHYSICAL, 
    CHOOSING_TICKET, INSERTING_COINS, INSERTING_CCARD, LOGGING_IN, PRINTING_TICKET, 
    CREATING_USER
}
